### ISSUE TITLE
hi 😎

### ISSUE THREAD

**Issue by Novola** [TeamJormungand/Konas-0.5.2#13]
charlie is big iqless skid xd 😎😎😎
![image](https://user-images.githubusercontent.com/61128456/108137215-5efc9300-70b3-11eb-9ee8-70ce2d8bd27a.png)
me clientside server packet

**Comment by B2H990** [comment]
please post a higher resolution image so we can understand the problem thank you.

**Comment by Novola** [comment]
> please post a higher resolution image so we can understand the problem thank you.

user error get glasses
