### ISSUE TITLE
make open src when

### ISSUE THREAD

**Issue by aesthetic0001** [TeamJormungand/Konas-0.5.2#16]
make it open src so ppl can easily check for rats and modify it?

**Comment by KohimaNayagato** [comment]
are you fucking stupid, time to "release src" of precompiled obfuscated binaries 🤡

**Comment by L-Nadav** [comment]
As a wise man once said, trol - Bella

**Comment by aesthetic0001** [comment]
provide a dump then?

**Comment by charlie353535** [comment]
Look at the two JARs, and a decompilation of the (not obfed) first jar in recaf. Come back after reading it properly

**Comment by aesthetic0001** [comment]
ok ty
