### ISSUE TITLE
Super based.

### ISSUE THREAD

**Issue by Lqnz** [TeamJormungand/Konas-0.5.2#8]
lol nice

**Comment by Crystallinqq** [comment]
unbased and uncool*

**Comment by NirvanaNevermind** [comment]
> unbased and uncool*

@Crystallinqq mad

**Comment by Lqnz** [comment]
> unbased and uncool*

mad cuz not qq crack

**Comment by Crystallinqq** [comment]
> > unbased and uncool*
> 
> mad cuz not qq crack

why would i crack a soon to be qAL customers client?

**Comment by Crystallinqq** [comment]
> > unbased and uncool*
> 
> @Crystallinqq mad

mad cuz cant dump qAL

**Comment by B2H990** [comment]
> > > unbased and uncool*
> > 
> > 
> > @Crystallinqq mad
> 
> mad cuz cant dump qAL

*Uses kernel injector and native dumper*

can't wait to see your countermeasure for that 🥱
